apiVersion: hpc.rosalita.github.io/v1
kind: DistributedJob
metadata:
  name: lottery-setforlife
spec:
  workerReplicas: 4
  image: lottery-analyser:latest
  command:
    - "/app/analyser"
    - "--game=setforlife"
    - "--chunk-size=2000000"
    - "--limit=5"
